In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv(r"F:\Car Performance Prediction\car prediction.csv")

In [4]:
dataset

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  origin  
0            70       1  
1            70       1  
2            70       1  
3            70       1  
4            70       1  
..          ...     ...  
393          82       1  
394          82       2  
395          82       1  
396          82       1  
397          82       1  

[398 rows x 8 columns]

In [5]:
dataset.shape

(398, 8)

In [6]:
#checking null values
dataset.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
dtype: bool

In [7]:
#no need for label encoding caz all of them are numerical
#no need for onehotencoding as there is no textual or categorical data

In [8]:
#splitting the values in x and y
x=dataset.iloc[:,1:8].values
y=dataset.iloc[:,0:1].values

In [9]:
x.shape

(398, 7)

In [10]:
y.shape

(398, 1)

In [11]:
#testing the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
import pickle
pickle.dump(mlr,open("mileage.pkl","wb"))

In [14]:
#predicting
y_pred=mlr.predict(x_test)

In [15]:
y_pred

array([[12.94323127],
       [24.06639807],
       [11.66747054],
       [21.14187061],
       [17.41518278],
       [29.8015473 ],
       [33.28389686],
       [23.60344459],
       [14.27048745],
       [26.44578809],
       [33.73042195],
       [33.97441625],
       [21.44722841],
       [26.74992667],
       [16.18298308],
       [30.31272689],
       [28.73867767],
       [28.89986161],
       [17.49681223],
       [30.64170151],
       [15.54417103],
       [24.71332798],
       [27.03473827],
       [19.98806975],
       [29.25649127],
       [28.24129936],
       [30.59723091],
       [30.28459261],
       [29.21158162],
       [18.26856411],
       [20.745642  ],
       [31.19340255],
       [21.48492048],
       [32.16707352],
       [23.87333121],
       [25.70349373],
       [21.38130409],
       [16.97016383],
       [31.74078803],
       [ 8.86382402],
       [10.07876716],
       [13.69907178],
       [26.07248438],
       [29.98680088],
       [31.4451476 ],
       [22

In [16]:
y_test

array([[14. ],
       [25. ],
       [13. ],
       [21. ],
       [18. ],
       [35. ],
       [34.1],
       [20. ],
       [15. ],
       [23.5],
       [40.9],
       [37.2],
       [18. ],
       [23. ],
       [15.5],
       [35.7],
       [31. ],
       [27. ],
       [18. ],
       [37.3],
       [15.5],
       [23. ],
       [24. ],
       [18. ],
       [34.5],
       [25.4],
       [36.1],
       [34. ],
       [30. ],
       [16. ],
       [18.6],
       [37. ],
       [15. ],
       [33.5],
       [22.4],
       [24. ],
       [19. ],
       [16.9],
       [31.9],
       [12. ],
       [14. ],
       [15. ],
       [27.4],
       [23.7],
       [32. ],
       [24. ],
       [22.5],
       [16.5],
       [21. ],
       [26. ],
       [41.5],
       [29. ],
       [15. ],
       [30. ],
       [15. ],
       [10. ],
       [18. ],
       [20.2],
       [36. ],
       [17. ],
       [18. ],
       [26.5],
       [18. ],
       [22. ],
       [12. ],
       [14. ],
       [15

In [17]:
x_test

array([[8.000e+00, 3.510e+02, 1.530e+02, 4.129e+03, 1.300e+01, 7.200e+01,
        1.000e+00],
       [4.000e+00, 1.400e+02, 7.500e+01, 2.542e+03, 1.700e+01, 7.400e+01,
        1.000e+00],
       [8.000e+00, 3.020e+02, 1.400e+02, 4.294e+03, 1.600e+01, 7.200e+01,
        1.000e+00],
       [4.000e+00, 1.200e+02, 8.700e+01, 2.979e+03, 1.950e+01, 7.200e+01,
        2.000e+00],
       [6.000e+00, 2.320e+02, 1.000e+02, 3.288e+03, 1.550e+01, 7.100e+01,
        1.000e+00],
       [4.000e+00, 7.200e+01, 6.900e+01, 1.613e+03, 1.800e+01, 7.100e+01,
        3.000e+00],
       [4.000e+00, 8.600e+01, 6.500e+01, 1.975e+03, 1.520e+01, 7.900e+01,
        3.000e+00],
       [4.000e+00, 1.400e+02, 9.000e+01, 2.408e+03, 1.950e+01, 7.200e+01,
        1.000e+00],
       [8.000e+00, 4.000e+02, 1.500e+02, 3.761e+03, 9.500e+00, 7.000e+01,
        1.000e+00],
       [6.000e+00, 1.730e+02, 1.100e+02, 2.725e+03, 1.260e+01, 8.100e+01,
        1.000e+00],
       [4.000e+00, 8.500e+01, 6.500e+01, 1.835e+03, 1.730e+0

In [18]:
#checking accuracy of the model
from sklearn.metrics import r2_score
accuracy=r2_score(y_test,y_pred)

In [19]:
accuracy

0.8210810978705724

In [20]:
dataset.head(1)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   

   model year  origin  
0          70       1

In [21]:
y_p=mlr.predict([[9,305,130,3504,15,70,2]])

In [22]:
y_p

array([[16.50890919]])

# Decision Tree Regressor

In [23]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [24]:
dtr_pred=dtr.predict(x_test)

In [25]:
dtr_pred

array([15. , 25.5, 14. , 19. , 19. , 31. , 31.8, 21. , 15. , 26.8, 31.8,
       31.8, 21. , 26. , 15. , 32. , 27. , 26.6, 16. , 33.8, 16. , 25.5,
       25. , 19. , 34.2, 24.2, 32.1, 31. , 32. , 15. , 19.2, 32.4, 15. ,
       32. , 17.6, 23. , 15. , 15.5, 33. , 12. , 14. , 16. , 28.4, 33.7,
       32.9, 20. , 24. , 16. , 19. , 31. , 34.5, 25. , 13. , 28. , 18. ,
       10. , 21. , 19.8, 32. , 18.1, 18.5, 25. , 19. , 23. , 13. , 16. ,
       14. , 16. , 25.5, 15. , 37.7, 12. , 25. , 19. , 24. , 30. , 33.5,
       31. , 30.5, 15. ])

In [26]:
y_test

array([[14. ],
       [25. ],
       [13. ],
       [21. ],
       [18. ],
       [35. ],
       [34.1],
       [20. ],
       [15. ],
       [23.5],
       [40.9],
       [37.2],
       [18. ],
       [23. ],
       [15.5],
       [35.7],
       [31. ],
       [27. ],
       [18. ],
       [37.3],
       [15.5],
       [23. ],
       [24. ],
       [18. ],
       [34.5],
       [25.4],
       [36.1],
       [34. ],
       [30. ],
       [16. ],
       [18.6],
       [37. ],
       [15. ],
       [33.5],
       [22.4],
       [24. ],
       [19. ],
       [16.9],
       [31.9],
       [12. ],
       [14. ],
       [15. ],
       [27.4],
       [23.7],
       [32. ],
       [24. ],
       [22.5],
       [16.5],
       [21. ],
       [26. ],
       [41.5],
       [29. ],
       [15. ],
       [30. ],
       [15. ],
       [10. ],
       [18. ],
       [20.2],
       [36. ],
       [17. ],
       [18. ],
       [26.5],
       [18. ],
       [22. ],
       [12. ],
       [14. ],
       [15

In [27]:
x_test

array([[8.000e+00, 3.510e+02, 1.530e+02, 4.129e+03, 1.300e+01, 7.200e+01,
        1.000e+00],
       [4.000e+00, 1.400e+02, 7.500e+01, 2.542e+03, 1.700e+01, 7.400e+01,
        1.000e+00],
       [8.000e+00, 3.020e+02, 1.400e+02, 4.294e+03, 1.600e+01, 7.200e+01,
        1.000e+00],
       [4.000e+00, 1.200e+02, 8.700e+01, 2.979e+03, 1.950e+01, 7.200e+01,
        2.000e+00],
       [6.000e+00, 2.320e+02, 1.000e+02, 3.288e+03, 1.550e+01, 7.100e+01,
        1.000e+00],
       [4.000e+00, 7.200e+01, 6.900e+01, 1.613e+03, 1.800e+01, 7.100e+01,
        3.000e+00],
       [4.000e+00, 8.600e+01, 6.500e+01, 1.975e+03, 1.520e+01, 7.900e+01,
        3.000e+00],
       [4.000e+00, 1.400e+02, 9.000e+01, 2.408e+03, 1.950e+01, 7.200e+01,
        1.000e+00],
       [8.000e+00, 4.000e+02, 1.500e+02, 3.761e+03, 9.500e+00, 7.000e+01,
        1.000e+00],
       [6.000e+00, 1.730e+02, 1.100e+02, 2.725e+03, 1.260e+01, 8.100e+01,
        1.000e+00],
       [4.000e+00, 8.500e+01, 6.500e+01, 1.835e+03, 1.730e+0

In [28]:
dtr_accuracy=r2_score(y_test,dtr_pred)

In [29]:
dtr_accuracy

0.8531671850592621

In [30]:
dataset.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   

   model year  origin  
0          70       1  
1          70       1

In [31]:
dtr_p=dtr.predict([[8,350,165,3693,11.5,70,1]])

In [32]:
dtr_p

array([16.])

# Random Forest Regressor

In [33]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr.fit(x_train,y_train)

C:\Users\Preeti uppala\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [44]:
#predicting with random forest regressor

In [35]:
rfr_pred=rfr.predict(x_test)

In [36]:
rfr_pred

array([14.33 , 23.909, 14.192, 20.808, 18.31 , 30.65 , 33.374, 21.864,
       14.905, 26.335, 36.414, 36.893, 19.247, 26.598, 16.262, 31.828,
       27.872, 27.076, 17.459, 32.651, 15.85 , 23.474, 23.798, 20.117,
       32.129, 27.772, 33.573, 30.577, 31.486, 16.575, 19.032, 33.005,
       18.468, 32.384, 20.907, 23.945, 18.66 , 15.877, 33.657, 11.98 ,
       13.79 , 15.351, 28.208, 32.413, 28.572, 22.061, 19.791, 14.635,
       21.629, 30.38 , 33.874, 25.54 , 16.339, 27.793, 15.348, 12.037,
       18.431, 23.808, 31.598, 16.989, 19.626, 25.022, 18.98 , 20.859,
       13.01 , 14.815, 13.48 , 17.547, 24.394, 14.34 , 35.772, 13.075,
       23.232, 18.564, 23.897, 28.797, 28.063, 31.101, 28.953, 14.481])

In [43]:
y_test

array([[14. ],
       [25. ],
       [13. ],
       [21. ],
       [18. ],
       [35. ],
       [34.1],
       [20. ],
       [15. ],
       [23.5],
       [40.9],
       [37.2],
       [18. ],
       [23. ],
       [15.5],
       [35.7],
       [31. ],
       [27. ],
       [18. ],
       [37.3],
       [15.5],
       [23. ],
       [24. ],
       [18. ],
       [34.5],
       [25.4],
       [36.1],
       [34. ],
       [30. ],
       [16. ],
       [18.6],
       [37. ],
       [15. ],
       [33.5],
       [22.4],
       [24. ],
       [19. ],
       [16.9],
       [31.9],
       [12. ],
       [14. ],
       [15. ],
       [27.4],
       [23.7],
       [32. ],
       [24. ],
       [22.5],
       [16.5],
       [21. ],
       [26. ],
       [41.5],
       [29. ],
       [15. ],
       [30. ],
       [15. ],
       [10. ],
       [18. ],
       [20.2],
       [36. ],
       [17. ],
       [18. ],
       [26.5],
       [18. ],
       [22. ],
       [12. ],
       [14. ],
       [15

In [38]:
rfr_acc=r2_score(y_test,rfr_pred)

In [39]:
rfr_acc

0.902138962177367

In [40]:
dataset.head(1)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   

   model year  origin  
0          70       1

In [41]:
rfr_p=rfr.predict([[8,307,130,3504,12,70,1]])

In [42]:
rfr_p

array([17.361])

# Hence random forest regressor has highest accuracy